version: 0.0
os: linux
files:
  - source: ./idle-counter-0.0.1-SNAPSHOT.jar
    destination: /tmp
  - source: /start.sh
    destination: /tmp/scripts
hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user